### ISSUE TITLE
Json 형태의 결과 파일 생성: -j 옵션

### ISSUE THREAD

**Issue by Min-Ho-Kim** [Min-Ho-Kim/Dexter#4]
Create Json result file - dexter-result.json. eg) -j

D:\dev\dexter\20160811_dexter\cli\dexter-cli_0.10.3_64\bin>dexter2.bat -u yes.ho -p yes.ho -j

D:\dev\dexter\20160811_dexter\cli\dexter-cli_0.10.3_64\bin>java -Xms256m -Xmx786m -XX:MaxPermSize=256m -jar dexter-executor.jar -u yes.ho -p yes.ho -j
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

===== Starting Dexter Analysis =====
- Loaded cppcheck 0.10.3
- Loaded findbugs 0.10.3
- Loaded dexter-opensource 0.10.3
- Loaded dexter-vd-cpp 0.10.3

== Defects Report ==
analyze synchronously...
Exception in thread "main" java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
        at com.google.common.io.Files$FileByteSink.<init>(Files.java:195)
        at com.google.common.io.Files$FileByteSink.<init>(Files.java:189)
        at com.google.common.io.Files.asByteSink(Files.java:186)
        at com.google.common.io.Files.asCharSink(Files.java:232)
        at com.google.common.io.Files.write(Files.java:508)
        at com.google.common.io.Files.append(Files.java:492)
        at com.samsung.sec.dexter.executor.cli.CLIResultFile.writeJsonResultFilePrefix(CLIResultFile.java:42)
        at com.samsung.sec.dexter.executor.cli.CLIAnalysisResultHandler.handleBeginnigOfResultFile(CLIAnalysisResultHandler.java:101)
        at com.samsung.sec.dexter.executor.cli.CLIAnalysisResultHandler.handleAnalysisResult(CLIAnalysisResultHandler.java:64)
        at com.samsung.sec.dexter.executor.DexterAnalyzerThread.run(DexterAnalyzerThread.java:102)
        at com.samsung.sec.dexter.executor.DexterAnalyzer.runSync(DexterAnalyzer.java:79)
        at com.samsung.sec.dexter.executor.cli.Main.analyzeSynchronously(Main.java:204)
        at com.samsung.sec.dexter.executor.cli.Main.analyze(Main.java:129)
        at com.samsung.sec.dexter.executor.cli.Main.main(Main.java:74)

**Comment by Minjung-Baek** [comment]
▶ 코드에서 옵션 두개 바뀐 것 같은데, 수정해야 할 것 같습니다
위치 : DexterCLIOption.java : 144

"j" : json / "x" : xml

> ```
>     if (cmd.hasOption("j")) {
>         this.isJsonFile = true;
>         createXmlResultFile(filename);
>     }
> 
>     if (cmd.hasOption("x")) {
>         this.isXmlFile = true;
>         createJsonResultFile(filename);
>     } 
> ```
