### ISSUE TITLE
XML 형태의 결과 파일 생성: -X 옵션 (파일명 뒤에 타임스탬프 추가)

### ISSUE THREAD

**Issue by Min-Ho-Kim** [Min-Ho-Kim/Dexter#7]
Create XML result file with timestamp - dexter-result_yyyyMMddhh:mm:ss.xml. eg) -X

D:\dev\dexter\20160811_dexter\cli\dexter-cli_0.10.3_64\bin>dexter2.bat -u yes.ho -p yes.ho -X

D:\dev\dexter\20160811_dexter\cli\dexter-cli_0.10.3_64\bin>java -Xms256m -Xmx786m -XX:MaxPermSize=256m -jar dexter-executor.jar -u yes.ho -p yes.ho -X
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

===== Starting Dexter Analysis =====
- Loaded cppcheck 0.10.3
- Loaded findbugs 0.10.3
- Loaded dexter-opensource 0.10.3
- Loaded dexter-vd-cpp 0.10.3

== Defects Report ==
analyze synchronously...
Exception in thread "main" java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
        at com.google.common.io.Files$FileByteSink.<init>(Files.java:195)
        at com.google.common.io.Files$FileByteSink.<init>(Files.java:189)
        at com.google.common.io.Files.asByteSink(Files.java:186)
        at com.google.common.io.Files.asCharSink(Files.java:232)
        at com.google.common.io.Files.write(Files.java:508)
        at com.google.common.io.Files.append(Files.java:492)
        at com.samsung.sec.dexter.executor.cli.CLIResultFile.writeXml2ResultFilePrefix(CLIResultFile.java:53)
        at com.samsung.sec.dexter.executor.cli.CLIAnalysisResultHandler.handleBeginnigOfResultFile(CLIAnalysisResultHandler.java:109)
        at com.samsung.sec.dexter.executor.cli.CLIAnalysisResultHandler.handleAnalysisResult(CLIAnalysisResultHandler.java:64)
        at com.samsung.sec.dexter.executor.DexterAnalyzerThread.run(DexterAnalyzerThread.java:102)
        at com.samsung.sec.dexter.executor.DexterAnalyzer.runSync(DexterAnalyzer.java:79)
        at com.samsung.sec.dexter.executor.cli.Main.analyzeSynchronously(Main.java:204)
        at com.samsung.sec.dexter.executor.cli.Main.analyze(Main.java:129)
        at com.samsung.sec.dexter.executor.cli.Main.main(Main.java:74

**Comment by Minjung-Baek** [comment]
▶ NullPointerException도 throw 하고 확인해봤더니, 아래처럼 xml 파일에 결함정보는 쓰여지긴 하는데, 에러는 동일하네요. 
자세한 사항은 좀 더 확인해보고 다시 추가하겠습니다. 


minjung.baek@dexter-Samsung-Desktop-System:~/CLI_Re/dexter-cli_0.10.2_64/bin$ ##./dexter2.sh -X -u minjung.baek -p vlgur253

===== Starting Dexter Analysis =====
 - Loaded dexter-opensource 0.10.2
 - Loaded dexter-vd-cpp 0.10.2
 - Loaded cppcheck 0.10.2
 - Loaded findbugs 0.10.2

== Defects Report ==
analyze synchronously...
★ ERROR : null (see ../log/dexter-executor.log file for more information)
 - /home/minjung.baek/securityAndCustomTC/secu/7.c
    > Total Defects: 2
    > sec_cij_exec / CRI / 1
       └ 6 Insecure input value injected from scanf[/home/minjung.baek/securityAndCustomTC/secu/7.c:5] to inVal
    > sec_bof_scanf_format / CRI / 1
       └ 5 scanf without field width limits can crash with huge input data.
Exception in thread "main" java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
        at com.google.common.io.Files$FileByteSink.<init>(Files.java:195)
        at com.google.common.io.Files$FileByteSink.<init>(Files.java:189)
        at com.google.common.io.Files.asByteSink(Files.java:186)
        at com.google.common.io.Files.asCharSink(Files.java:232)
        at com.google.common.io.Files.write(Files.java:508)
        at com.google.common.io.Files.append(Files.java:492)
        at com.samsung.sec.dexter.executor.cli.CLIResultFile.writeXml2ResultFilePostfix(CLIResultFile.java:119)
        at com.samsung.sec.dexter.executor.cli.CLIAnalysisResultHandler.handleEndOfResultFile(CLIAnalysisResultHandler.java:129)
        at com.samsung.sec.dexter.executor.cli.CLIAnalysisResultHandler.handleAnalysisResult(CLIAnalysisResultHandler.java:95)
        at com.samsung.sec.dexter.executor.DexterAnalyzerThread.run(DexterAnalyzerThread.java:102)
        at com.samsung.sec.dexter.executor.DexterAnalyzer.runSync(DexterAnalyzer.java:79)
        at com.samsung.sec.dexter.executor.cli.Main.analyzeSynchronously(Main.java:203)
        at com.samsung.sec.dexter.executor.cli.Main.analyze(Main.java:129)
        at com.samsung.sec.dexter.executor.cli.Main.main(Main.java:74)

---------------------------------------------------------------------------------------------------------


minjung.baek@dexter-Samsung-Desktop-System:~/CLI_Re/dexter-cli_0.10.2_64/bin$ ## cat dexter-result_20160819123249.xml
        <error filename="/home/minjung.baek/securityAndCustomTC/secu/7.c">
                <defect checker="sec_cij_exec">
                        <occurence startLine="6" endLine="6"  message="Insecure input value injected from scanf[/home/minjung.baek/securityAndCustomTC/secu/7.c:5] to inVal" />
                </defect>
                <defect checker="sec_bof_scanf_format">
                        <occurence startLine="5" endLine="5"  message="scanf without field width limits can crash with huge input data." />
                </defect>
        </error>

**Comment by Minjung-Baek** [comment]
▶ NullPointerException도 throw 하고 확인해봤더니, 아래처럼 xml 파일에 결함정보는 쓰여지긴 하는데, 에러는 동일하네요. 

> minjung.baek@~/CLI_Re/dexter-cli_0.10.2_64/bin$ cat dexter-result_20160819123249.xml
> 
> ```
>     <error filename="/home/minjung.baek/securityAndCustomTC/secu/7.c">
>             <defect checker="sec_cij_exec">
>                     <occurence startLine="6" endLine="6"  message="Insecure input value injected from scanf[/home/minjung.baek/securityAndCustomTC/secu/7.c:5] to inVal" />
>             </defect>
>             <defect checker="sec_bof_scanf_format">
>                     <occurence startLine="5" endLine="5"  message="scanf without field width limits can crash with huge input data." />
>             </defect>
>     </error>
> ```
